services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: y0na
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - social_network
  # social_network:
  #   build: ./
  #   container_name: social_network
  #   depends_on:
  #     - postgres
  #   networks:
  #     - shopping
  #   ports:
  #     - "3000:3000"

networks:
  social_network:
    driver: bridge

volumes:
  pgdata:
